### ISSUE TITLE
The difference between your implementation and  official  implementation 

### ISSUE THREAD

**Issue by LJill** [ChristophReich1996/Involution#11]
Thanks for your work . But I have a question , the  official  implementation can't change the output channel,  why yours can?

**Comment by ChristophReich1996** [comment]
Hey @LJill, good question, so in case the number of input channels differs from the number of output channels, a 1X1 convolution is utilized to adapt the channels, of the input tensor.
https://github.com/ChristophReich1996/Involution/blob/2263b6237f837b63051de12773e917b67a740abf/involution/involution.py#L72-L74
Cheers
Christoph
