### ISSUE TITLE
Whether this module support the case that kernel's width not equal height?

### ISSUE THREAD

**Issue by entropyfeng** [ChristophReich1996/Involution#8]
I have read part of  your code and was very excited about the results your code. However, after read  your repo, I am left with some concerns:
1、`The 2D involution takes the following parameters.` shoud be modified to `The 3D involution takes the following parameters.` of your description of  3D involution fragment in the readme file ?
2、The implementation of `nn.Unfold` by  [offical pytorch](https://pytorch.org/docs/stable/generated/torch.nn.Unfold.html?highlight=unfold#torch.nn.Unfold) describe the  output of the function ，as the issue #7 describe, when i change the line 6 `involution_2d = Involution2d(in_channels=4, out_channels=8)` to `involution_2d = Involution2d(in_channels=4, out_channels=8,kernel_size=(2,3))` in examples.py the exception will appear 
```Traceback (most recent call last):
  File "C:/Users/Desktop/InvolutionA/examples.py", line 8, in <module>
    output = involution_2d(input)
  File "D:\anaconda\envs\yolov5\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\Desktop\InvolutionA\involution\involution.py", line 127, in forward
    input_unfolded = input_unfolded.view(batch_size, self.groups, self.out_channels // self.groups,
RuntimeError: shape '[2, 1, 8, 6, 68, 68]' is invalid for input of size 450432

Process finished with exit code 1
```
thanks for your response.

**Comment by ChristophReich1996** [comment]
Hey, thanks for your interest, so using a non-square kernel is kinda problematic because the kernel tensor is constructed using two 1 X 1 convolutions  (reduce and span mapping). Thus, the shape of the unfold operation with a non-square kernel can not always be reached. A possible solution would be to use (zero) padding which, however, would be not very clean since the padded elements of the kernel tensor would be zero-valued...
Do you have a better solution in mind?

PS: Thanks for indicating the typo in the README!

Cheers
Christoph

**Comment by entropyfeng** [comment]
Thanks, the reason why i take this non-square parameter is to reduce computation, as the Inception  use 1×3 conv kernel and 3×1 conv kernel to instead 3×3 conv kernel. Will the idea work on this Involution module?

Cheers

**Comment by ChristophReich1996** [comment]
Hi, so as long as the same shape is preserved through padding there should be no problems in using a non-square kernel. Only in the edge case if a non-square kernel is without preserving the original size or a downscaled size, which can not be obtained by the reduce mapping, the span mapping, and the pooling layer, a shape mismatch occurs.

**Comment by entropyfeng** [comment]
Ok, I already know what the problem is, thank you very much.
